// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructure.Models;

public partial class Inventario
{
    public int Id { get; set; }

    public int? ProductoId { get; set; }

    public int? CantidadStock { get; set; }

    public string UbicacionAlmacen { get; set; }

    public virtual Producto Producto { get; set; }
}