// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructure.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public double? Precio { get; set; }

    public int? CategoriaId { get; set; }

    public string ImagenUrl { get; set; }

    public virtual Categoria Categoria { get; set; }

    public virtual ICollection<DetallesPedido> DetallesPedidos { get; set; } = new List<DetallesPedido>();

    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();
}